### ISSUE TITLE
Debug files exist in master. Possible way to fix it :thinking: 

### ISSUE THREAD

**Issue by ghost** [KinetixGaming/acmeinventoryprogram#1]
:wave: There seems to be some debug files in commit history.

```
git checkout --orphan new-msater
git rm --cached -r .
git rm --cached -r *
git add .
git commit -m 'initial'
git push origin new-master
```

that should clean it up and then make `new-master` the default branch and then delete `main` and `master` and then rename `new-master` to `master` :grinning:

**Comment by KinetixGaming** [comment]
Debug files have been removed and master has been overwritten by new-master
