### ISSUE TITLE
Add steepestascent as maintainer of this repo

### ISSUE THREAD

**Issue by ghost** [KinetixGaming/acmeinventoryprogram#2]
Hi @KinetixGaming 

This app looks sweet. I'd :heart: to help out. might be useful if i was added as a maintainer to this repo. what do you think :grin:? !

:point_right: this might be useful [doc](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository)

**Comment by KinetixGaming** [comment]
A request has been made to add you as a Collaborator
